# Generated by Django 6.0.1 on 2026-01-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feature_type', models.CharField(choices=[('line', 'Line/Route'), ('polygon', 'Polygon/Zone'), ('circle', 'Circle'), ('rectangle', 'Rectangle')], max_length=20)),
                ('geometry', models.JSONField()),
                ('style', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sidc', models.CharField(help_text='Symbol ID Code (MIL-STD-2525)', max_length=30)),
                ('affiliation', models.CharField(choices=[('F', 'Friendly'), ('H', 'Hostile'), ('N', 'Neutral'), ('U', 'Unknown')], default='U', max_length=1)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
