# Generated by Django 6.0.1 on 2026-01-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('line', 'Line/Route'), ('polygon', 'Polygon/Zone'), ('circle', 'Circle'), ('rectangle', 'Rectangle'), ('arrow', 'Arrow/Direction')], max_length=20),
        ),
    ]
