# Generated by Django 6.0.1 on 2026-01-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_tools', '0002_alter_feature_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('line', 'Line/Route'), ('polygon', 'Polygon/Zone'), ('circle', 'Circle'), ('rectangle', 'Rectangle'), ('arrow', 'Arrow/Direction'), ('elevationProfile', 'Elevation Profile'), ('lineOfSight', 'Line of Sight')], max_length=20),
        ),
    ]
